name: Main Branch CI
on: 
  push:
    branches: 
      - main
      - feature/*
  
jobs:
  Build-Code:
    runs-on: ubuntu-latest
    steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
    - name: Display SemVer
      run: |
        echo "SemVer: $GITVERSION_SEMVER NugetVersion: $GITVERSION_NUGETVERSION"
